####LOAD THE DPLYR PACKAGE
require(dplyr)

##LET'S LOAD THE DATASET

store <- read.csv("FINAL DEPARTMENTAL STORE.csv")

###PART 1 : DATA TRANSFORMATION

###i.GET THE INFORMATION OF THE COLUMNS 4-10
###ii.WHERE PRODUCT_CATEGORY IS 'household'
###iii.ARRANGED IN ASCENDING ORDER OF QUANTITY_DEMANDED. 




###PART 2 : STATISTICAL INTERPRETATION

###i. FIND THE AVERAGE AND SUMMATION OF QUANTITY_DEMANDED
###ii. GROUPED BY PRODUCT CATEGORY



